package moreco.searchlib;

import java.util.ArrayList;
import java.util.List;

public class SearchLibTest {

    public static void main(String[] args) {
//        testEnglish();
        testJapanese();
    }

    private static void testJapanese() {
        String searchText = "私は部屋の鍵でルームに";
        List<SearchDataRecord> searchData = createDataTestJapanese();
        List<SearchDataRecord> searchResult = SearchLib.search(searchText, SearchLib.LANG_CODE_JAPANESE, searchData, 0);
        for (int i = 0; i < searchResult.size(); i++) {
            System.out.println(searchResult.get(i).getSearchData());
        }
    }

    private static void testEnglish() {
        String searchText = "have key room you";
        List<SearchDataRecord> searchData = createDataTestEnglish();
        List<SearchDataRecord> searchResult = SearchLib.search(searchText, SearchLib.LANG_CODE_ENGLISH, searchData, 0);
        for (int i = 0; i < searchResult.size(); i++) {
            System.out.println(searchResult.get(i).getSearchData());
        }
    }

    private static List<SearchDataRecord> createDataTest(String[] testData) {
        List<SearchDataRecord> result = new ArrayList<SearchDataRecord>();
        for (int i = 0; i < testData.length; i++) {
            result.add(new TestSearchData(testData[i]));
        }

        return result;
    }

    private static List<SearchDataRecord> createDataTestEnglish() {
        String[] testData = {
        		"How to go to New National Stadium",
        		"Can I go there by {0}?",
        		"I'd like to check in. My name is {0}.",
        		"This is a confirmation slip.",
        		"I have no reservation. Do you have a room available?",
        		"One single room for 2 nights.",
        		"One double room for 1 night.",
        		"One twin room for 3 nights.",
        		"Is this room with a bath / shower?",
        		"Mr (Ms){0}. Yes, we have your reservation.",
        		"We have a room available. We can provide a room for you.",
        		"Unfortunately, we have no rooms available.",
        		"Please fill out this form.",
        		"Will you make payment by credit card?",
        		"OK, can I have your credit card, please.",
        		"Thank you very much. (returning the credit card.)",
        		"We may ask you for a prepayment. The amount is {0} Dollars.",
        		"Thank you very much. This is the receipt.",
        		"Your room number is {0}. This is the room key.",
        		"Your room is on second floor.",
        		"Your room in on third floor.",
        		"Please wait one minute. We will take you to the room now.",
        		"Please leave your key at the front desk when you go out.",
        		"You can have breakfast at the cafeteria.",
        		"Breakfast is included in the room rate.",
        		"The cafeteria is on the ground (first) floor. It is over there. (pointing in the direction)",
        		"You can enjoy dinner at a restaurant nearby or the restaurant on the first floor of our hotel.",
        		"If you have any requests, please call to our front desk.",
        		"Please check out by {0} o'clock.",
        		"Enjoy your stay.",
        		"Can I use the room now?",
        		"Can I ask you to bring my baggage to my room?",
        		"Can I leave my baggage at your hotel?",
        		"Can I have my baggage that I asked you to keep? My name is {0}.",
        		"(I will go out now.) Please keep my key, thanks.",
        		"Certainly.",
        		"(Coming back to the hotel) Can I have my key? My room number is {0}.",
        		"Here's your key.",
        		"Would you call me a taxi please?",
        		"Certainly. I have arranged a taxi for you.  Please wait in the lobby.  Mr.{0}. The taxi has arrived.",
        		"I have locked myself out.",
        		"Can I ask you to arrange this tour for me? (Showing an ad provided at the hotel)",
        		"Do you have a facsimile?",
        		"Do you have public access computers with Internet connection?",
        		"I'll be back late tonight.",
        		"What time do you close the front door?",
        		"Do you have any suggestions for good restaurants in the area?",
        		"Can I ask you for a wakeup call at {0} am tomorrow morning? My name is {1}, room number is {2}.",
        		"Can I ask you to do my laundry?",
        		"When will it be ready?",
        		"Do you have coinoperated laundry machines?",
        		"I want to check out please.",
        		"Thank you very much. Just a moment please.",
        		"Your bill is {0}dollars. This is the bill statement.",
        		"I think there is a mistake in the calculation of my bill.",
        		"What is this charge for? (showing the statement.)",
        		"I didn't make any phone calls.",
        		"I didn't watch any movies.",
        		"You had a coke from the mini bar. This is fee.",
        		"Please put your signature here, thanks.",
        		"I'd like my valuables back.",
        		"Certainly. Here you are.",
        		"Thank you very much for your stay.",
        		"I/We enjoyed my/our stay. Thank you very much.",
        		"Please take your shoes off at the entrance.",
        		"Please put these slippers on while walking inside the building.",
        		"Please take your shoes off before you go inside your room.",
        		"Please don't step on the tatami floor with your slippers on.",
        		"A tea serving set and a thermos with hot water are provided in your room. Please enjoy tea anytime.",
        		"Daiyokujou (big bath room) is here. (Showing a small map of the building.)",
        		"Daiyokujou (big bath room) for men and women are separated. Please be careful when you go inside the bath room.",
        		"This symbol is for the bath for women and this symbol is for men. (Showing the symbols)",
        		"Please don't pull out the drain plug of the bath tub.",
        		"You can wear Yukata for pajamas or as a robe.",
        		"You can go out of your room wearing Yukata.",
        		"You can have dinner wearing Yukata if you like.",
        		"After taking the bath, you can put on Yukata.",
        		"Please bring the bath towel and the hand towel in your room when you go to Daiyokujou (big bath room).",
        		"In the Daiyokujou (big bath room), shampoo, hair conditioner and soap are provided.",
        		"Please don't put the hand towel into the bath tub.",
        		"You are only to go inside the bath tub after you washed your body, please.",
        		"It is better not to bring precious belongings to the changing (dressing) room of Daiyokujou (big bath room).",
        		"Please do not walk in your room in the slippers from the toilet room.",
        		"We will bring your dinner to your room at {0}.",
        		"Are you finished? Can I take the dishes away?",
        		"Dinner will be ready at {0}. Please come to the cafeteria at that time.",
        		"We will come to your room to prepare the futons.",
        		"May I come in? I have come to lay out your futons for you.",
        		"We will come to fold up the futons at {0} tomorrow morning.",
        		"Good morning. I am here to fold up the futons.",
        		"It's so sunny today. Perfect for traveling, isn't it!",
        		"Have a nice trip!",
        		"We hope you enjoy your stay at our Ryokan again.",
        		"Hello, ABC hotel, how may I help you?",
        		"Hello? I'd like to contact a guest staying at your hotel. Would you please help me?",
        		"Certainly. Could you tell me your name and the name of the guest you'd like to contact ?",
        		"I'd like to talk to Mr. John Smith. My name is Hanako Suzuki.",
        		"OK. Please hold the line.",
        		"Hello, Mr.Smith? You have a phone call from Hanako, calling from Tokyo. Will you accept this call?",
        		"Yes, please. Thank you very much.",
        		"Hello? I called him, but he was out, unfortunately. Shall I tell him that you tried to get in touch with you, when he comes back?",
        		"Yes, please. My name is Hanako Suzuki, calling from Japan. Please give him my phone number, just in case. The number is {0}.",
        		"Sure, I will send this message to Mr. Smith.",
        		"Hello / What would you like to have?",
        		"(As you point at a photo in Menu) I will have this one and this one.",
        		"One Hamburger and a Medium Coffee please.",
        		"One Hamburger and a Coffee please.",
        		"We have 3 sizes for coffee, Small, Medium and Large.. Which size would you like?",
        		"Small one, please.",
        		"2 Coffee's Please. One is Small and the other is a Medium.",
        		"We have 3 sizes, Short, Tall and Grande. Which size would you like?",
        		"Tall one please.",
        		"One hamburger and one small French Fry Anything else?",
        		"That's all.",
        		"For here, or to go /takeout / (or to go)",
        		"Eat in or take away? [ UK, Australia, New Zealand ]",
        		"For here please.",
        		"To go please.",
        		"${0}.{1}",
        		"Thank you very much.",
        		"Do you have any combo's",
        		"Yes, we have these combos. [pointing at the menu]",
        		"Yes. This is a combo. This combo includes a Hamburger, a Drink, a Salad or French fries.",
        		"Yes, This is a combo. You can select a salad or a French Fries. Which would you like to have?",
        		"We have juices, soda(pop)",
        		"I will have a Combo A with a large coke.",
        		"Sorry, large drink doesn't come with this combo. You can select only a medium sized drink for this combo.",
        		"I will have Combo B with a small order of French fries and an iced coffee?",
        		"Sorry, we don't have iced coffee in our menu. How about a regular coffee instead? : )",
        		"Take a number and wait at your table, thanks.",
        		"Number 5, please. Here you are.",
        		"Just leave the tray there. We'll take care of.",
        		"Please bring back the tray to that section.",
        		"We have hot and iced coffee. Which do you prefer?",
        		"Hot coffee, please.",
        		"At reception / entrance",
        		"Are you open ?",
        		"Good evening. How many?",
        		"We are 4",
        		"Table for 2 please.",
        		"No Smoking or Smoking?",
        		"Nosmoking section please.",
        		"Smoking section please.",
        		"Can we (I) sit at that table? (pointing)",
        		"I am so sorry, there is no table available now. We will have to ask you to wait.",
        		"OK, How long wait?",
        		"There is a waiting time of 30 minutes or so.",
        		"OK, We (I) will wait.",
        		"Sorry, we(I) have no time to wait. Thank you.",
        		"Excuse me, where can I hang my jacket?",
        		"We have an area where you can hang your jacket.",
        		"What time is the last order?",
        		"Can I have a menu? / Can we have menu’s?",
        		"We (I) will let you know when we have decided.",
        		"Please let me know when you have decided.",
        		"Are you ready to order?",
        		"Excuse me. Can you take our (my) order, please.",
        		"What would you like to drink?",
        		"2 beers",
        		"A glass of white wine and a beer.",
        		"What kind of beer?",
        		"Imported or domestic?",
        		"We will have a bottle of white(red) wine.",
        		"I will have this. (From pointing at an entree in the menu)",
        		"Do you have any specials of the day?",
        		"Yes, we have three specials. Here. (pointing to a section in the Menu)",
        		"OK, I will have this one.",
        		"Which one do you recommend?",
        		"Do you have any vegetarian dishes?",
        		"I’d like to have beef. Do you have any in your menu?",
        		"I’d like to have pork. Do you have any in your menu?",
        		"I’d like to have chicken. Do you have any in your menu?",
        		"I’d like to have vegetable. Do you have any in your menu?",
        		"I’d like to have a cooked fish. Do you have any in your menu?",
        		"I’d like to have a raw fish. Do you have any in your menu?",
        		"I’d like to have a salad. Do you have any in your menu?",
        		"Yes, we have. These here are beef. (pointing a section in the Menu)",
        		"Is it sweet?",
        		"Is it spicy?",
        		"Is it sour?",
        		"Is it salty taste?",
        		"Is it fried in oil?",
        		"Is it steamed?",
        		"Is it fried?",
        		"Is it cooked?",
        		"Is it raw",
        		"OK, I will have this and a cup of coffee.",
        		"When would you like to have your coffee.Before the meal? Or after the meal?",
        		"After the meal, please.",
        		"finished? (Waiter asking if you are finished eating the dish and if it is OK to take the dish away)",
        		"Check (Cheque) please.",
        		"Can I pay by credit card?",
        		"Certainly.",
        		"Sorry, we don’t accept payments by credit card.",
        		"OK, I will pay by cash.",
        		"Please give me a receipt.",
        		"Buying vegetables or fruits",
        		"I would like to buy 5 tomatoes.",
        		"I would like {0} pounds(kg) of apples.",
        		"This for 5 please. (By pointing at fruit that you don't know the name.)",
        		"Do you sell those in bulk?",
        		"Do you sell these by the pound (kg)?",
        		"Buying food at a Delicatessen",
        		"Do you have {0}?",
        		"Do you have Tofu products?",
        		"Can I have {0} for {1}?",
        		"I will take this for 3.  This is for 3?  No, the one on the left/right side of you.  This?  No, the one in front/back of you.",
        		"I will have a salad in a small/medium/large container.",
        		"These pickles please, {0} grams/ounces. (pointing with finger)",
        		"This cheese please, {0} grams.",
        		"This quiche for 2, please.",
        		"Can I have 2 or 3 slices of ham with bread, please?  What type of bread would you like?  What bread do you have?  We have .......  OK, I will take the first bread you mentioned.",
        		"Will you warm it up for me?",
        		"When is the 'use by date'?",
        		"Should I eat them today?",
        		"Fresh for a few days?",
        		"How long will it be fresh?",
        		"Do I need to keep them in fridge?",
        		"Buying meat",
        		"I will take this bacon, {0} ounces please.",
        		"I will take this ham, {0} ounces, please. I'd like it sliced.",
        		"I will take these Pork spareribs, {0} pounds please.",
        		"I will take these sausages, for 5 please.",
        		"I will take these Pork fillets, {0}(pieces) please.",
        		"Do you have minced pork?",
        		"I will take this beef, 3 (slices) please.",
        		"I will take this Chicken breast for one please.",
        		"Buying seafood]",
        		"{0} pounds of mussels please.",
        		"One lobster please.",
        		"I take this salmon, 3 (slices) please.",
        		"Is this fish good for Sushi? Is this fish fresh enough to eat as Sushi?",
        		"Can I eat this shellfish raw?",
        		"{0}pounds of shrimp please.",
        		"Buying sweets(desserts)",
        		"I will take this cake, 3 pieces please.",
        		"Do you include cooler(dried ice) to keep it cold for 1 hour?",
        		"5 cookies please.",
        		"2 cinnamon rolls please.",
        		"Others",
        		"I am looking for {0}. Where is it?",
        		"Where is the 'usedby date' printed on this milk carton?",
        		"Where can I return bottle empties.",
        		"I don't know how to use the water vending machine. Will you show me how to buy water from this machine?",
        		"Hello. How may I help you?",
        		"Just looking, thanks.",
        		"Yes. I am looking for {0} . Do you have them?",
        		"Yes, we have. Follow me. I will show you.",
        		"I am sorry, they are out of stock. It will take a few days before we have it in the store.",
        		"I am sorry, we don't carry them.",
        		"I am sorry, we can't help you..",
        		"Excuse me, Could you help me?",
        		"Sure. How may I help you?",
        		"I'd like the one in the window.",
        		"I'd like the one in that showcase.",
        		"I'd like the one on the shelf over there.",
        		"OK, I will get it for you.",
        		"Which one?",
        		"The second one in back from the right..",
        		"The third one in front from the left",
        		"This one?",
        		"Yes, that one.",
        		"Here you are.",
        		"Would you like to have this?",
        		"I am sorry. This wasn't exactly what I wanted.",
        		"Yes. I will take this.",
        		"Can I try this on?",
        		"Sure. The fitting room is over here.)",
        		"This is too big",
        		"Do you have this in a smaller size?",
        		"This is much too small.",
        		"Do you have this in bigger size?",
        		"What is your size?",
        		"My size is {0}.",
        		"I don't know my size in this country's standard, as I am a traveler.",
        		"Would you find the one that fits my size?",
        		"How about this one?",
        		"This fits my size. OK, I will take this.",
        		"This size doesn't fit me.",
        		"I am sorry. I will come back later.",
        		"I am sorry. I can't make a decision today.",
        		"OK, bye.",
        		"{0} dollar, please.",
        		"Can I pay by credit card?",
        		"What credit card do you have?",
        		"Visa.",
        		"We accept Visa and yes you can pay by credit card.",
        		"I am sorry, but we don't accept credit cards.",
        		"OK, I will pay by cash.",
        		"Could you wrap this separately, please?",
        		"Could you giftwrap this please?",
        		"Can I have one more extra paper/plastic bag? This is for a souvenir.",
        		"When does the sale start?",
        		"We are having a sale now.",
        		"These are on sale.",
        		"Can you give me a discount?",
        		"We are selling these at discount prices already.",
        		"Buying Overthecounter drugs at a pharmacy.",
        		"Do you have medicine for diarrhea?",
        		"Do you have medicine for constipation?",
        		"Do you have medicine for a cold?",
        		"Do you have medicine for headache?",
        		"Do you have medicine for stomachache?",
        		"Do you have medicine for heartburn?",
        		"Do you have medicine for a temperature?",
        		"Do you have medicine for nausea?",
        		"Do you have medicine for a toothache?",
        		"Do you have medicine for hemorrhoids?",
        		"Do you have medicine for {0}?",
        		"You need a prescription to buy the medicine.",
        		"Yes. This is medicine for {0}.",
        		"Which one do you recommend for me?",
        		"What is the condition of your illness. Is it serious? Or just a light illness?",
        		"If it is not so serious, this medicine would be of help.",
        		"If it is serious, this medicine would be of help. However, you should read the introduction carefully and follow the recommendations.",
        		"OK, I will take this.",
        		"Could you fill this prescription, please?",
        		"Sure. Please wait. I will get ready for you.",
        		"How do I take this?",
        		"You should take it 3 times a day, after meals. Take only 1 tablet at one time.",
        		"You should take it 1 time a day, before meals. Take 2 tablets at one time.",
        		"The explanation of how to take this medicine is written here. (pointing by finger)",
        		"Would you please write down here how I should take this medicine just in case I forget your advice.",
        		"Do you have an ointment for itching?",
        		"Do you have insectsprotection lotion?",
        		"Do you have eye drops?",
        		"Do you have plaster?",
        		"Do you have cold/warm compresses?",
        		"Do you have cotton swabs?",
        		"Do you have Vitamin C?",
        		"Do you have Vitamin E?",
        		"Do you have Sunprotection lotion?",
        		"Do you have diapers?",
        		"Do you have instant baby foods?",
        		"On Streets",
        		"Excuse me. May I ask you something?",
        		"I'm looking for a train station. The name is {0} Station. Do you know where it is?",
        		"I'm looking for a subway station. The name is {0} station. Do you know where it is?",
        		"I'm looking for a bus stop. The bus is for {0} and the name of the bus stop is {1} . Do you know where it is?",
        		"I'm looking for {0}. Do you know where it is?",
        		"I have lost my way to {0}.",
        		"I am going to {0}. Is this the right way to take?",
        		"I am going to {0}. Is this right direction to go?",
        		"Would you show me where we are now on this map?",
        		"Would you show me where my designation is on this map?",
        		"Is it near here?",
        		"Is it far from here?",
        		"Do you think I can get there by walking?",
        		"How long does it take to get there?",
        		"Is there a Koban (Police Station) near here?",
        		"Is there a public phone near here?",
        		"I see. Thank you very much.",
        		"It was great help! Thank you very much!",
        		"At Stations",
        		"What's the fare for {0} Station?",
        		"A oneway ticket for {0} Station, please.",
        		"A roundtrip ticket for {0} Station, please.",
        		"I bought the wrong ticket, do you think I could refund this?",
        		"What time does the train leave?",
        		"What is the arrival time?",
        		"Where can I get the train for {0}?",
        		"Where is train line no.{0}?",
        		"Is this train for {0}?",
        		"Does this train stop at {0} Station?",
        		"Can I reach {0} Station by this train?",
        		"Do I have to change trains?",
        		"Which station do I change the trains at?",
        		"This station is {0} , is that correct?",
        		"I took a wrong train, how do I go back to this station {0}.?",
        		"Getting on a bus",
        		"Does this bus go to {0}?",
        		"Where can I get bus No. {0} ?",
        		"What is the fare?",
        		"How do I pay the fare?",
        		"How many stops to go before this bus stop?",
        		"The next bus stop is {0} , is that correct?",
        		"Getting on a taxi",
        		"Where is the Taxi stand?",
        		"Where can I catch a Taxi?",
        		"Take me to this address, please. (showing the address)",
        		"To {0} please.",
        		"How long does it take to get there?",
        		"What will be the fare?",
        		"Thank you very much. Keep the change.",
        		"(Calling a taxi by telephone）",
        		"Hello, a taxi please. It's at 10:00am, tomorrow. The address is {3} Street {1} {2}. The phone number is {4}. My name is {5}. Thank you very much.",
        		"Others",
        		"Excuse me, do you happen to know where the rest room is?",
        		"Hello, how may I help you?",
        		"Yes, I'd like to use the Internet.",
        		"How many hours would you like to use?",
        		"I'd like 30 minutes.",
        		"I'd like 1 hours.",
        		"I'd like 2 hours.",
        		"What fee's do you charge?",
        		"Is it prepaid system?",
        		"Is it a deferred payment system?",
        		"How much is it for 1 hour?",
        		"We have a prepaid system. It's a hourly charge. You are charged a hourly fee even if you only are online for 30 minutes.",
        		"We have prepaid system. The fee is ${0} per hour. It is ${1} for 2 hours including tax.",
        		"We charge after you use the service. Please come to the counter after you are finished using.",
        		"OK, I'd like the 1 hour rate.",
        		"What type of computer would you like?",
        		"We have PC Notebooks and Desktops and Mac's.",
        		"A Notebook PC with Windows, please.",
        		"A Desktop PC with Windows please.",
        		"A Mac please.",
        		"Do you have a PC with English(Japanese) OS?",
        		"Yes. We have three computes with English(Japanese) OS.",
        		"No, we don't have.",
        		"Yes. The computer No.5 is English (Japanese) OS.",
        		"No,. All the computers here are of Italian OS.",
        		"OK, I will use a PC with Italian OS.",
        		"OK, I will use a PC with English OS.",
        		"OK, No. 5, 7 and 8 computers have English OS. Please use one of them.",
        		"Check please",
        		"3 hours use in total. ${0}. Thanks.",
        		"Thank you very much.",
        		"Can I get an Internet connection with my mobile PC?",
        		"If you have a LAN card, yes, you can.",
        		"Unfortunately, we don't offer only Internet connection.",
        		"boot my computer",
        		"reboot my computer",
        		"turn off my computer",
        		"Keystrokes",
        		"copy and paste",
        		"cut and paste",
        		"undo",
        		"save",
        		"press the right(left) arrow",
        		"press the up arrow",
        		"press the down arrow",
        		"hold Ctrl key down and then press the right arrow.",
        		"place the pointer over the text and then click the mouse.",
        		"scroll up / scroll down",
        		"drag the pointer to a designated area",
        		"drag and drop",
        		"Open Program Menu, and Click on {0}.",
        		"set up",
        		"configure",
        		"change configurations in the dialog box.",
        		"enable {0}",
        		"disable {0}",
        		"enable / disable JavaScript scripting",
        		"The default installation settings.",
        		"Select {0} radio button.",
        		"Check {0}(item name)",
        		"Remove the check at {0}(item name)",
        		"Web site(s)",
        		"hook up to the Internet",
        		"I have an Internet connection.",
        		"have access to {0}",
        		"view",
        		"step back to the previous page",
        		"step forward to the next page",
        		"save",
        		"press the right(left) arrow",
        		"press the up arrow",
        		"press the down arrow",
        		"refresh the page. (または） Reload the page.",
        		"enlarge the window",
        		"reduce the window",
        		"{0} appears",
        		"That page appears.",
        		"an error message appears.",
        		"display",
        		"The browser displays an error message",
        		"Display this page.",
        		"Bring the window forward (When multiple windows are open) Bring the window forward",
        		"move the cursor over {0}",
        		"move the cursor over the text.",
        		"Click on it.",
        		"reach the web page B by clicking a link on the web page A.",
        		"log in to {0}",
        		"perform a search on a Search Engine",
        		"Search for the keyword phrase {0}.",
        		"Search results",
        		"text and images that appear on the web page.",
        		"adjust line spacing and margins",
        		"change the appearance of text on the page",
        		"line break(s)",
        		"blank line(s)",
        		"line(s)",
        		"typo(s)",
        		"a source HTML file(s)",
        		"Underlined text",
        		"Bold text",
        		"A web page controlled by Style Sheet.",
        		"Space",
        		"Free space web server.",
        		"My computer froze.",
        		"A frozen computer.",
        		"Shut down the frozen window.",
        		"My computer froze. I can't even reboot. Can I turn it off?",
        		"Illegal access",
        		"block illegal access with a fire wall.",
        		"There's something wrong with this PC. Maybe It has a virus.",
        		"detect viruses on your computer.",
        		"This computer is infected with a virus.",
        		"I've got a virus on my PC",
        		"A file infected with a virus.",
        		"A file with a virus.",
        		"clean up viruses with antivirus software.",
        		"I have tried hooking up to the Internet, but I can't.",
        		"Maybe it is not a problem on your computer. There must be a server problem at your ISP.",
        		"It displays corrupted text and it can't be fixed although I used the function 'encode'.",
        		"Maybe it can not be helped. The OS is not a Japanese one.",
        		"As this is a shared computer, you'd better clear the cache and the history before you leave.",
        		"How do I clear the history?",
        		"Select Option from the menu, and then, click on 'Clear the history' on the dialog box appeared.",
        		"You can clear cache with the same way.",

        };
        return createDataTest(testData);
    }

    private static List<SearchDataRecord> createDataTestJapanese() {
        String[] testData = {
        		"どのように新国立競技場に行けますか?",
        		"あそこに{0}で行けますか?",
        		"チェックインをお願いします。名前は{0}です。",
        		"これが予約確認書です。",
        		"予約してません。空いている部屋はありますか？",
        		"シングル１部屋で、２泊です。",
        		"ダブルルーム１部屋で１泊です。",
        		"ツインルーム１部屋で３泊です。",
        		"バスルーム/シャワーつきの部屋ですか？",
        		"ご予約頂いている{0}様ですね。",
        		"空いている部屋はございます。どうぞ、お泊まり下さい。",
        		"あいにく、空いている部屋はございません。",
        		"こちらのフォームにご記入下さい。",
        		"お支払はクレジットカードですか？",
        		"では、クレジットカードをお願い致します。",
        		"有難うございました。（カードを返す。）",
        		"料金は前払いとなっております。{0}ドルをお願い致します。",
        		"有難うございました。こちらが領収書です。",
        		"お部屋の番号は{0}になります。こちらが鍵です。",
        		"お部屋は２階です。",
        		"お部屋は３階です。",
        		"今、係りの者がお部屋までご案内いたします。",
        		"外出の際は、鍵をフロントにお預け下さい。",
        		"朝食はカフェテリアでお取り頂けます。",
        		"朝食は料金に含まれています。",
        		"カフェテリアは１階、あちらにございます。 (方向を手で示しながら。）",
        		"夕食は近くのレストラン、または当ホテル１階のレストランをご利用下さい。",
        		"何かご要望がございましたら、フロントにお申し付け下さい。",
        		"チェックアウトは{0}時までにお願いします。",
        		"ご滞在をお楽しみ下さい。",
        		"今から部屋を使えますか？",
        		"荷物を部屋に運んでもらえますか？",
        		"荷物を預かってもらえますか？",
        		"預かって頂いていた荷物をお願いします。名前は{0}です。",
        		"（今から外出します。）鍵を預かって下さい。",
        		"かしこまりました。",
        		"（外出から帰り、）鍵を下さい。部屋の番号は{0}です。",
        		"どうぞ、こちらです。",
        		"タクシーを呼んでもらえますか？",
        		"かしこまりました。  ただ今、手配しましたので、ロビーでお待ち下さい。 {0}様、タクシーが参りました。",
        		"カギを部屋の中に置いたまま、ドアを閉めてしまいました。",
        		"ツアーの手配をお願いできますか？このツアーに参加したいんです。（ホテルにあったパンフレットを見せる。）",
        		"ファクシミリはありますか？",
        		"インターネットが使えるコンピュータはありますか？",
        		"今夜、戻るのが遅くなります。",
        		"表のドアは何時に締まりますか？",
        		"この近くにおすすめのレストランありませんか？",
        		"明日朝、モーニングコールを{0}時にお願いします。部屋番号{1}の{2}です。",
        		"洗濯をお願いします。",
        		"仕上りはいつになりますか？",
        		"コインランドリーはありますか？",
        		"チェックアウトお願いします。",
        		"有難うございます。少々お待ち下さい。",
        		"料金は{0}ドルとなります。 明細書はこちらです。",
        		"料金に計算違いがある様なんですが。",
        		"これは何の料金ですか？（明細を見せながら）",
        		"電話は使いませんでしたよ。",
        		"映画は見ていないです。",
        		"ミニバーのコーラをお飲みになりましたので、その料金です。",
        		"それでは、こちらにサインをお願いします。",
        		"預けていた貴重品を出してください。",
        		"かしこまりました。こちらです。",
        		"ご利用誠に有難うございました。",
        		"私/私達にとって良い滞在となりました。お世話になりました。",
        		"靴は玄関でお脱ぎ下さい。",
        		"建物内ではスリッパをご利用下さい。",
        		"室内では靴をお脱ぎください。",
        		"スリッパで畳の部屋に入らないで下さい。",
        		"ポットとお茶がお部屋に用意してあります。ご自由にお飲み下さい。",
        		"大浴場はここにあります。（略図を見せながら。）",
        		"男湯と女湯に分かれています。入る前にご注意下さい。",
        		"女湯のマークはこれです。男湯のマークはこれです。（マーク（漢字）を見せながら）",
        		"浴槽の詮は抜かないで下さいね。",
        		"浴衣は室内着、またはパジャマとしてご利用下さい。",
        		"浴衣姿で部屋の外を歩いてもかもいません。",
        		"浴衣姿で夕食をお目し上がりになってもかまいません。",
        		"入浴後、浴衣を着用頂けます。",
        		"大浴場に行く時は部屋のバスタオルとタオルを持参して下さい。",
        		"大浴場にシャンプー、リンス、せっけんはあります。",
        		"浴槽に、タオルを入れないで下さい。",
        		"浴槽には身体を洗ってから入ります。",
        		"大浴場の脱衣所には貴重品を持って行かない様にしてください。",
        		"トイレのスリッパで室内は歩かないで下さい。",
        		"夕飯は{0}時にお部屋にお持ちします。",
        		"お食事はお済ですか？お下げしてよろしいでしょうか。",
        		"夕飯は{0}時にご用意いたします。時間になりましたら、食堂までお越し下さい。",
        		"夜、お布団を敷きにまいります。",
        		"失礼します、お布団を敷きいたします。",
        		"明日の朝は{0}時にお布団を上げに参ります。",
        		"おはようございます、お布団を上げに参りました。",
        		"今日は快晴で、ご旅行に最高ですね！",
        		"良いご旅行を！",
        		"当旅館へのまたのお越しをお待ちしております。",
        		"（電話に出る） はい、ABCホテルでございます。",
        		"もしもし、そちらに宿泊されているゲストの方と連絡を取りたいのですが、お願いできますでしょうか。",
        		"承知しました。そちら様のお名前と呼び出すお客様のお名前をお教え下さい。",
        		"ジョン・スミス氏をお願いします。私の名前は鈴木花子です。",
        		"では、お呼びしてみますので少々お待ち下さい。",
        		"もしもしスミス様でございますか。鈴木花子さまという方からお電話が入っております。おつなぎして宜しいでしょうか。",
        		"（スミス氏）はい、お願いします。",
        		"お待たせしました。残念ながら外出中の様です。戻られましたら電話があった事をお伝えしましょうか？",
        		"お願いします。私の名前は鈴木花子です。日本から電話しています。念のため電話番号をお伝えします。電話番号は{0}です。",
        		"承知しました。確かにお伝えいたいます。",
        		"いらっしゃいませ /ご注文をどうぞ。",
        		"（メニューの写真を指差しながら） これを１つとこれを１つ下さい。",
        		"ハンバーガー１つとコーヒーのMを１つ。",
        		"ハンバーガー１つとコーヒーを１つ。",
        		"コーヒーにはS,M,Lの３サイズございますが、どれにいたしますか？",
        		"S をください。",
        		"コーヒーのSとMを１つずつ下さい。 （=コーヒーを２つ下さい。１つはS,もう１つはMで。）",
        		"(コーヒーには)ショート、トール、グランデの３サイズございますが、どれになさいますか？",
        		"トールを下さい。",
        		"ハンバーガー１つとポテトのSを１つ。以上でよろしいでしょうか。",
        		"はい、それで全部です。",
        		"こちらでお召し上がりですか？お持ち帰りですか？ （北米英語圏での言い方））",
        		"こちらでお召し上がりですか？お持ち帰りですか？ (イギリス、オーストラリア、ニュージーランドでの言い方）",
        		"こちらで。",
        		"持ちかえりで。",
        		"{0}ドル{1}（セント）です。",
        		"ありがとうございました。",
        		"セットメニューはありますか？",
        		"はい、ございます。こちらがセットメニューです。（メニューを指差しながら。）",
        		"はい、ございます。こちらのセットメニューがハンバーガー、お飲み物、そしてサラダまたはフライドポテトのセットとなります。",
        		"はい、ございます。こちらがセットメニューです。サラダまたはフライドポテトのどちらかをお選び頂けます。 どちらになさいますか？",
        		"お飲み物はオレンジジュース、炭酸水、コーヒーまたは紅茶がございます。 どれになさいますか？",
        		"セットAをコーラのLで。",
        		"申し訳ございません。このセットにLサイズのお飲み物はつきません。Mサイズのみです。",
        		"セットBをポテトのSとアイスコーヒーとで。",
        		"申し訳ございません。アイスコーヒーはご用意しておりません。 代りにコーヒーはいかがでしょうか？",
        		"番号札をお持ちになりテーブルでお待ち下さい。",
        		"5番の方、お待たせしました。どうぞ。",
        		"トレイはそのままでけっこうです。こちらで片付けます。",
        		"トレイはあちらの場所にお戻し下さい。",
        		"コーヒーはアイスとホットがありますが、どちらになさいますか？",
        		"ホットをお願いします。",
        		"エントランスで",
        		"開いてますか？（今、営業中ですか？）",
        		"こんばんは、いらっしゃいませ。 何名様で？",
        		"４名です。",
        		"２名で座るテーブルをお願いします。",
        		"喫煙席、禁煙席のどちらに？",
        		"禁煙席をお願いします。",
        		"喫煙席をお願いします。",
        		"あのテーブル（席）に座っていいですか？ （指差しながら）",
        		"すみません、只今、満席なので、お待ち頂くことになります。",
        		"待ち時間はどれくらいですかね？",
        		"待ち時間は30分ほどになります。",
        		"それじゃ、、待ちます。",
        		"残念ですね。それじゃあまたにします． （残念ながら待てません。お世話をお掛けしました。）",
        		"すみません、どこに上着を掛けていいですか？",
        		"上着を掛ける場所はこちらにあります。",
        		"ラストオーダーは何時ですか？",
        		"メニューをください。（私に/ 私たちに。）",
        		"決まったらお呼びしますので。",
        		"お決まりになりましたらお呼びください。",
        		"ご注文よろしいですか？（お決まりになりましたか？）",
        		"オーダーお願いします。",
        		"お飲み物は何にいたしましょうか？",
        		"ビールを２つ。",
        		"グラスワイン１つとビール１つ。",
        		"どのビールになさいますか？",
        		"輸入ビールと国産ビールのどちらに？",
        		"白（赤）ワインをボトルで１本。",
        		"これ下さい。 (メニュー内の料理名を指差しながら）",
        		"今日のスペシャルメーニューはありますか？",
        		"はい、ございます。こちらの３品が今日のスペシャルメーニューです。 （メニュー内を指差しながら）",
        		"それじゃあ、これをください。",
        		"おすすめはどの料理ですか？",
        		"ベジタリアン料理はありますか？",
        		"牛肉料理が食べたいんですけど、メニューにありますか？",
        		"豚肉料理が食べたいんですけど、メニューにありますか？",
        		"鶏肉料理が食べたいんですけど、メニューにありますか？",
        		"野菜料理が食べたいんですけど、メニューにありますか？",
        		"調理した魚料理が食べたいんですけど、メニューにありますか？",
        		"生の魚料理が食べたいんですけど、メニューにありますか？",
        		"サラダが食べたいんですけど、メニューにありますか？",
        		"はい、ございます．こちらが牛肉料理です。 （メニューを指差しながら）",
        		"甘い（味付け）ですか？",
        		"辛いですか？",
        		"酸っぱいですか？",
        		"塩味ですか？",
        		"揚げ物ですか？",
        		"蒸し物ですか？",
        		"炒め物ですか？",
        		"煮物ですか？",
        		"生ですか？",
        		"分かりました。それじゃあ、これとコーヒーを１つ。",
        		"コーヒーはいつお持ちしましょう？食前ですか？食後ですか？",
        		"食後にお願いします。",
        		"こちらお下げしてよろしいですか？ (接客係が空になった皿を下げていいか聞く）",
        		"勘定お願いします。",
        		"クレジットカードで支払えますか？",
        		"はい、（カードでのお支払を）承っております。",
        		"すみません、カードでのお支払は承っておりません。",
        		"分かりました。現金で払います。",
        		"レシート（領収書）を下さい。",
        		"（市場で）野菜・果物を買う",
        		"トマトを５コ、買いたいのですが。",
        		"リンゴを{0}ポンド(キロ）下さい。",
        		"これを５コ下さい。 （名前の分からない果物を指差しながら）",
        		"それはばら売りしていますか？",
        		"これはポンド（キロ）売りですか？",
        		"デリで総菜を買う",
        		"{0}はありますか？",
        		"豆腐製品はありますか？",
        		"{0} を{1}つ下さい。（もらえますか？）",
        		"これを3つ下さい。  これを３つですか？  いいえ、その（店員から見て）左横/左側にあるのです。 これですか？  いいえ、その（店員から見て）前/奥にあるのです。",
        		"このサラダを下さい。（量は）小/中/大サイズの容器で下さい。",
        		"このピクルスを{0}グラム/オンス下さい。 （指差しながら）",
        		"このチーズを{0}グラム下さい。（指差しながら）",
        		"このキッシュを２つ下さい。",
        		"このハムを２，３枚下さい。パンに挟んで下さい。  パンはどれにしますか？  どんな種類のパンがありますか？     などがありますが。  じゃあ、一番目に言ったパンをお願いします。",
        		"温めてもらえますか？",
        		"賞味期限はいつですか？",
        		"これ(ら)は今日中に食べた方が良いですか？",
        		"これは数日間もちますか？",
        		"どれくらいもちますか？",
        		"冷蔵庫で保管した方が良いですか。",
        		"(肉屋で）肉を買う",
        		"このベーコンを{0}オンス下さい。（指差しながら）",
        		"このハムを{0}オンス下さい。スライスして下さい。",
        		"スペアリブを{0}ポンド下さい。",
        		"このソーセージを５本下さい。",
        		"豚ヒレ肉を{0}枚下さい。",
        		"豚のひき肉はありますか？",
        		"この牛肉を３枚下さい。",
        		"鶏のムネ肉を１つ下さい。",
        		"(魚屋で）魚介類を買う",
        		"ムール貝を{0}ポンド下さい。",
        		"ロブスターを１匹下さい。",
        		"このシャケの切り身を３枚下さい。",
        		"この魚はスシにして食べられますか？",
        		"この貝は生で食べれますか？",
        		"小エビを{0}ポンド下さい。",
        		"ケーキを買う",
        		"このケーキを３つ下さい。",
        		"１時間用の保冷剤(ドライアイス）を入れてもらえますか？",
        		"クッキーを５枚下さい。",
        		"シナモンロールを２つ下さい。",
        		"その他",
        		"～を探してます。どこにありますか？",
        		"この牛乳、賞味期限はどこに書いてありますか？",
        		"空き瓶の返却はどこですか？",
        		"飲料水の販売機の使用方法が分かりません。使い方を教えてもらえますか。",
        		"いらっしゃいませ。何かお探しですか。",
        		"いいえ、ちょっと見ているだけですので。",
        		"はい、～を探しています。ありますか？",
        		"それなら、こちらにございます。場所をご案内します。",
        		"申し訳ございません。只今、在庫切れです。入荷まで数日掛かってしまいます。",
        		"申し訳ございません。それは取り扱っておりません。",
        		"お役に立てず、申し訳ございません。",
        		"すみません、ちょっとお願いできますか？ （手助けしてもらえますか？）",
        		"はい、どうぞ。何でしょうか。",
        		"ウインドウに飾ってあるものがほしいのですが。",
        		"あのショーケースにあるものがほしいのですが。",
        		"あちらの商品棚にあるものがほしいのですが。",
        		"分かりました。今、お取りします。",
        		"どれになりますか？",
        		"右から2番目奥にあるのです。",
        		"左から3番目の手前にあるのです。",
        		"こちらですか？",
        		"はい、それです。",
        		"はい、どうぞ。",
        		"こちらのご購入でよろしいですか？",
        		"すみません、私がほしかったのとはちょっと違いました。",
        		"はい、それを下さい。",
        		"これを試着してよろしいですか？",
        		"はい、どうぞ。試着室はこちらです。",
        		"ちょっと大き過ぎるようです。",
        		"もう少し小さいサイズはありますか？",
        		"ちょっと小さ過ぎるようです。",
        		"もう少し大きいサイズはありますか？",
        		"サイズはおいくつですか？",
        		"私のサイズは{0}です。",
        		"旅行者なので、この国のサイズ基準が分かりません。",
        		"私に合いそうなサイズのものを選んでもらえませんか？",
        		"これはいかがでしょうか。",
        		"このサイズはピッタリです。これにします。",
        		"このサイズは合いません。",
        		"残念ですが、またにします。",
        		"すみません、決められないのでまたにします。",
        		"分かりました。またの機会に。",
        		"{0}ドルです。",
        		"クレジットカードで支払えますか？",
        		"どこのカードですか？",
        		"Visaカードです。",
        		"Visaカードでしたら承ります。",
        		"すみません、カードでのお支払はお受けしておりません。",
        		"分かりました。現金で支払います。",
        		"これを別々に包んでもらえますか？",
        		"プレゼント用に包んでもらえますか？",
        		"お土産用なので紙袋/プラスチック袋をもう一枚余分にもらえますか？",
        		"バーゲンセールはいつからですか？",
        		"只今、バーゲンセール中です。",
        		"こちらはセール品です。",
        		"値引きしていただけますか？",
        		"こちらは既に値引きして販売しています。",
        		"薬局で市販薬品を買う",
        		"下痢止めの薬はありますか？ （下痢＝ダイアゥリーア）",
        		"便秘薬はありますか？ （便秘＝コンスティペイション）",
        		"風邪薬はありますか？",
        		"頭痛薬はありますか？ (頭痛＝ヘデック）",
        		"胃痛薬はありますか？ （胃I痛＝ストマケイク）",
        		"むねやけ止めの薬はありますか？ （むねやけ＝ハートバーン）",
        		"解熱薬はありますか？",
        		"吐き気を止める薬はありますか？ （吐き気＝ノーシャス）",
        		"歯痛を止める薬はありますか？ （歯痛＝トゥースィック）",
        		"痔に効く薬はありますか？ （痔＝ヘモ ゥロイド）",
        		"～の薬はありますか？",
        		"その薬の購入には処方箋が必要です。",
        		"はい、ございます。これが～の薬です。",
        		"どれがお勧めですか？",
        		"軽い症状ですか？重い症状ですか？",
        		"軽いのならこちらがお勧めです。",
        		"重いならこの薬がお勧めです。ただし、効き目が強いので使用方法を守って服用するよう、注意してください。",
        		"それではこれを下さい。",
        		"この処方箋の薬を下さい。",
        		"はい、分かりました。 今、薬をご用意しますので、お待ち下さい。",
        		"どのように飲むのですか？",
        		"1日3回、食後に服用してください。1回に１錠服用してください。",
        		"1日1回、食前に服用してください。1回に2錠服用してください。",
        		"服用方法はここに書いてあります。 （指差しながら）",
        		"念の為、服用方法をここに書いて下さい。 （このサンプルを見せながら ↓）",
        		"かゆみ止めの塗り薬はありますか？",
        		"虫除けのローションはありますか？",
        		"目薬はありますか？",
        		"バンソウコウはありますか？",
        		"冷湿布/温湿布はありますか？",
        		"綿棒はありますか？",
        		"ビタミンＣ剤はありますか？(ビタミン＝ヴァイタミン）",
        		"ビタミンE剤はありますか？",
        		"日焼け止めはありますか？",
        		"オムツはありますか？",
        		"インスタントの離乳食はありますか？",
        		"道で",
        		"すみません、ちょっとお尋ねします。",
        		"今、駅を探しています。駅名は{0}です。どこにありますでしょうか？",
        		"今、地下鉄の駅を探しています。駅名は{0}です。どこにありますでしょうか？",
        		"今、バス停を探しています。{0}行きのバスでバス停名は{1}です。どこにありますでしょうか？",
        		"今、{0}を探しています。どこにありますでしょうか？",
        		"{0}に行く途中で、今、道に迷っています。",
        		"{0}に行きたいのですが,この道で正しいですか？",
        		"{0}に行きたいのですが,この方向で正しいですか？",
        		"この地図で現在位置を教えて下さい。",
        		"この地図で私が行こうとしている場所の位置を教えて下さい。",
        		"ここから近いですか？",
        		"ここから遠いですか？",
        		"徒歩で行けますか？",
        		"どれくらいかかりますか？",
        		"この近くに交番はありますか？",
        		"この近くに公衆電話はありますか？",
        		"分かりました。有難うございました。",
        		"とても助かりました！有難うございました！",
        		"駅で",
        		"{0}駅までの乗車料金はいくらですか？",
        		"{0}駅までの片道キップを１枚下さい。",
        		"{0}駅までの往復キップを１枚下さい。",
        		"間違ったキップを買ってしまいました。払い戻しはできますか？",
        		"発車時刻は何時ですか？",
        		"到着時刻は何時ですか？",
        		"{0}行きの電車はどこで乗れますか？",
        		"{0}番線ホームはどこですか？",
        		"この電車は{0}行きですか？",
        		"この電車は{0}駅で停車しますか？",
        		"この電車で{0}駅に行けますか？",
        		"乗換えが必要ですか？",
        		"どの駅で乗り換える必要がありますか？",
        		"ここは{0}駅ですよね？",
        		"間違った電車に乗ってしまいました。どうすれば{0}駅に行けますか？（もどれますか？）",
        		"バスに乗る",
        		"このバスは{0}に行きますか？",
        		"{0}番のバスはどこで乗れますか？",
        		"乗車賃はいくらですか？",
        		"乗車賃はどうやって支払えばいいのですか？",
        		"このバス停まではあといくつバス停がありますか？",
        		"次のバス停は{0}ですよね？",
        		"タクシーに乗る",
        		"タクシー乗り場はどこですか？",
        		"どこでタクシーを拾えますか？",
        		"この住所までお願いします。（住所のメモを見せる）",
        		"{0}までお願いします。",
        		"時間はどれくらいかかりますか？",
        		"料金はどのくらいかかりますか？",
        		"有難うございました。お釣りはとっておいてください。",
        		"(電話でタクシーを呼ぶ）",
        		"タクシーの手配お願いします。 明日の午前{0}時にお願いします。 住所は{1}通り{2}番{3}です。 電話番号は{4}です。 名前は{5}です。宜しくお願い致します。",
        		"その他",
        		"すみません、トイレがどこにあるかご存知でしょうか？",
        		"いらっしゃいませ。",
        		"インターネットを利用したいんですけど。",
        		"何時間ご利用になりますか？",
        		"30分間利用したいんです。",
        		"1時間利用したいんです。",
        		"2時間利用したいんです。",
        		"料金の支払い方法はどの様な形ですか？",
        		"料金は前払いですか？",
        		"料金は後払いですか？",
        		"1時間いくらですか？",
        		"料金は前払いです。料金は１時間単位となっています。３０分間でも１時間料金となります。",
        		"料金は前払いです。料金は１時間ご利用で{0}ドルです。2時間では{1}ドルです。",
        		"料金は後払いです。ご利用後、カウンターにお越し下さい。",
        		"それでは1時間利用します。",
        		"どのタイプの機種をご利用されますか？",
        		"ノート型、デスクトップ型、マック機、ウェインドウズ機があります。",
        		"ノート型ウインドウズ機をお願いします。",
        		"デスクトップ型をお願いします。",
        		"マック機をお願いします。",
        		"ＯＳが英語（日本語）の機種はありますか？（英語圏外の国で）",
        		"はい、あります。英語（日本語）のＯＳのＰＣは３台あります。",
        		"申し訳ございませんが、ございません。",
        		"はい、あります。５番のＰＣが英語（日本語）のＯＳです。",
        		"申し訳ございません、全てイタリア語ＯＳです。",
        		"分かりました。それではイタリア語のＯＳでかまいません。",
        		"それでは、英語版（日本語版）を利用します。",
        		"分かりました。では、５番、７番、８番のＰＣが英語（日本語）ＯＳ機です。いずれかをご利用下さい。",
        		"支払いをお願いします。",
        		"３時間のご利用ですね。{0}ドルになります。",
        		"有難うございました。",
        		"自分のノートパソコン持ちこみでネット接続したいのですが、できますでしょうか？",
        		"はい。LANカードをお持ちでしたら可能です。",
        		"申し訳ございませんが、ネット回線接続のみのご利用はできません。",
        		"(私の)パソコンを立ち上げる。",
        		"パソコンを再起動する。",
        		"パソコンを終了する。",
        		"キーボード操作（キー入力）",
        		"コピーして貼りつける(動詞）",
        		"切りとって貼りつける(動詞）",
        		"元に戻す",
        		"保存する",
        		"右（左）矢印を押す",
        		"上矢印を押す",
        		"下矢印を押す",
        		"Ctrlキーを押しながら右矢印を押す",
        		"マウスのポインターをそのリンクに移動して、クリックする。",
        		"上に/ 下にスクロールする",
        		"マウスのドラッグで範囲指定する",
        		"ドラッグ＆ドロップする（動詞）",
        		"「プログラム」メニューを開き、{0}をクリック。",
        		"設定する",
        		"設定項目を設定する。",
        		"ダイアロボックス内の設定項目を変更する。",
        		"～を有効にする",
        		"～を無効にする",
        		"JavaScriptを無効/有効にする",
        		"インストール時の初期設定(値）",
        		"{0}のラジオボタンを選択する。",
        		"{0}(項目名)にチェックマークを入れる",
        		"{0}(項目名)のチェックマークを外す",
        		"ホームページ",
        		"パソコンをインターネットに接続する。",
        		"（私は）インターネット環境がある",
        		"～にアクセスする。",
        		"閲覧する",
        		"前ページに戻る",
        		"次のページへ進む",
        		"保存する",
        		"右（左）矢印を押す",
        		"上矢印を押す",
        		"下矢印を押す",
        		"ページを更新する",
        		"ウィンドウを拡大する",
        		"ウィンドウを縮小する",
        		"～が表示される",
        		"そのページが表示される",
        		"エラーメッセージが表示される",
        		"表示する",
        		"ブラウザーでエラーが表示される",
        		"このページを表示して下さい。",
        		"そのウインドウを手前にもってきなさい。 （複数ウインドウを開いている時））",
        		"～にカーソルを移動する。",
        		"そのテキストにカーソルを移動する。",
        		"それをクリックして。",
        		"ページＡにあるリンクをクリックしてページＢにアクセスする",
        		"～にログインする",
        		"サーチエンジンで検索する",
        		"キーワード {0}で検索する。",
        		"検索結果",
        		"そのウェブページに表示されるテキストとイメージ",
        		"ページの行間とマージンを調整する",
        		"ページのテキスト表示（見栄え）を変える",
        		"改行",
        		"空白の行",
        		"行",
        		"スペルミス",
        		"HTMLのソースファイル",
        		"下線のある文字",
        		"太文字",
        		"スタイルシートで制御されたページ",
        		"容量",
        		"無料ホームページ（サーバー）",
        		"パソコンがフリーズした。",
        		"フリーズしたパソコン（名詞）",
        		"フリーズしたウインドウを閉じる",
        		"パソコンがフリーズしてしまいました。再起動もできません。一度、電源を落としていいですか？",
        		"不正アクセス",
        		"ファイヤーウォールで不正アクセスをブロックする。",
        		"パソコンの具合が変です。ウイルスに感染しているみたいです。",
        		"ウイルスをスキャンする",
        		"このＰＣはウイルスに感染している。",
        		"私のパソコンがウイルスに感染した。",
        		"ウイルスに感染したファイル",
        		"ウイルスが入ったファイル",
        		"アンチウイルスソフトでウイルスを駆除する。",
        		"何度試してもインターネットにつながりません。",
        		"それは、パソコンの不具合でなくＩＳＰ側での問題だと思われます。",
        		"ページが文字化けしてしまいます。エンコードしても直りません。",
        		"OSが日本語でないので、しかたないのかもしれませｎ。",
        		"共有パソコンだから、使い終わったら（帰る前に）キャッシュと履歴をクリアにした方がいいよ。",
        		"履歴はどうやって削除するの？",
        		"メニューからオプションを選択して表示されたダイアログにある「履歴をクリア」をクリックすれば削除できるよ。",
        		"同じやり方でキャッシュもクリアできるよ。",

        };
        return createDataTest(testData);
    }

    /**
     * Data model used for testing.
     */
    static class TestSearchData implements SearchDataRecord
    {
        private String text;

        public TestSearchData(String text) {
            this.text = text;
        }

        @Override
        public String getSearchData() {
            return text;
        }
    }
}
